import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

import NavAction from "../components/navbutton";

const inter = Inter({ subsets: ["latin"] });

const filterBy = [
	{
		thing: "projects",
	},
	{
		thing: "research",
	},
];

const navActions = [
	{
		href: "/about",
		thing: "about",
	},
	{
		href: "/resume",
		thing: "resume",
	},
	{
		href: "/connect",
		thing: "connect",
	},
];

const data = [
	{
		id: "e",
		num: "1.",
		type: "research",
		title: "Reviewing How To Prevent a Climate Disaster by Bill Gates",
		date: "January 3, 2022",
	},
	{
		id: "d",
		num: "2.",
		type: "proj",
		title: "Interfacing Farmers in the US 2020",
		date: "January 3, 2022",
	},
	{
		id: "c",
		num: "3.",
		type: "research",
		title: "Visualizing and tracking US agricultral commodity flow",
		date: "December 18, 2022",
	},
	{
		id: "a",
		num: "4.",
		type: "proj",
		title: "Facebook Campaign Spending Interface",
		date: "May 30, 2022",
	},
	{
		id: "b",
		num: "5.",
		type: "proj",
		title: "Seek: a training data annotation platform",
		date: "Feburary 28, 2022",
	},
	{
		id: "a",
		num: "6.",
		type: "proj",
		title: "YOBO (You Only airBend Once)",
		date: "May 30, 2021",
	},
];

export default function Home() {
	const [showAbout, setShowAbout] = useState(true);

	function numberItems() {
		for (let idx = 0; idx <= data.length - 1; idx++) {
			let obj = data[idx];

			obj["num"] = idx;
		}
	}

	function handleAbout() {
		setShowAbout(!showAbout);
	}

	useEffect(() => {
		numberItems();
	}, []);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin={true}
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400&family=Open+Sans:wght@300;400&family=Work+Sans&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<main className="bg-white min-h-screen text-black tracking-tighter justify-center flex py-0 lg:py-4">
				<div className="w-[1200px]">
					<div className="bg-[#0099ff]">
						<div className="flex space-x-20 p-2 items-end">
							<div className="font-medium text-lg">MatthewBlog</div>
							<div className="text-base flex space-x-2">
								<div onClick={handleAbout}>
									<NavAction title="about" press={showAbout} />
								</div>
								<NavAction title="email" />
								<NavAction title="linkedin" />
								<NavAction title="github" />
								<NavAction title="resume" />
							</div>
						</div>
						{showAbout ? (
							<div className="p-2">
								<div>
									<span>
										I am a{" "}
										<a className="underline cursor-pointer underline-offset-2 decoration-white">
											software developer
										</a>{" "}
										who cares about advancing agriculture. We need to increase
										food production by 70% to feed 10 billion people by 2050.
										However, our world is getting hotter. We emit 51 billion
										tons of greenhouse gases every year with{" "}
										<a
											className="underline cursor-pointer underline-offset-2 decoration-white"
											href="https://www.climatewatchdata.org/ghg-emissions?breakBy=sector&chartType=percentage&end_year=2019&sectors=total-including-lucf&start_year=1990"
										>
											6.1 billion tons (12%) of ghg contributed by agriculture.
										</a>{" "}
										If we want to reach net-zero emissions and feed everyone,
										we're going to have to figure out how to grow plants and
										raise animals while reducing and eventually eliminating
										greenhouse gases.
									</span>
								</div>
								<div className="pt-2">
									<span className="">
										This blog is an effort to educate myself about the
										agriculture industry and agronomy. I love building things. I
										also want to develop my writing skills.{" "}
									</span>
								</div>
							</div>
						) : (
							<></>
						)}
					</div>
					<div className="bg-[#f6f6ef] h-screen">
						<div className="flex justify-center">
							<div className="w-4/12 text-base">
								<div className="grid grid-cols-2 py-2 divide-x-2">
									<div className="flex justify-center items-center space-x-3">
										<div className="h-3 w-3 bg-[#00ffe5]"></div>
										<div>projects</div>
									</div>
									<div className="flex justify-center items-center space-x-2">
										<div className="h-3 w-3 bg-[#FF6600]"></div>
										<div>research</div>
									</div>
								</div>
							</div>
						</div>

						<div className="grid grid-cols-1 divide-y">
							{data.map(({ num, id, type, title, date }) => {
								return (
									<div key={id} className="cursor-pointer px-3 py-1">
										<div className="px-3 py-1 flex items-start space-x-4">
											{type == "proj" ? (
												<div className="h-6 w-6 bg-[#00ffe5] flex justify-center items-center">
													{num}
												</div>
											) : (
												<div className="h-6 w-6 bg-[#FF6600] flex justify-center items-center">
													{num}
												</div>
											)}
											<div>
												<div style={{ fontFamily: inter }} className="text-lg">
													{title}
												</div>

												<div className="text-[#828282] text-sm">{date}</div>
											</div>
										</div>
									</div>
								);
							})}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
